name: dart_basic
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ">=2.18.0 <4.0.0"

# Add regular dependencies here.
dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.0
dependencies:
  http: ^1.3.0
  intl: ^0.18.0
