name: dart_basic
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.18.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  intl: ^0.18.0 # Menambahkan dependensi intl
  intl: ^0.18.0 # Adding intl dependency
dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.0

dev_dependencies:
  test: ^1.24.0
